"""add desctiption

Revision ID: 0496f7402fa3
Revises: 069ef3d141b6
Create Date: 2021-01-14 23:36:09.864028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0496f7402fa3'
down_revision = '069ef3d141b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'description')
    # ### end Alembic commands ###
