"""create patient data

Revision ID: 069ef3d141b6
Revises: 2566e1460825
Create Date: 2021-01-13 22:52:55.895882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069ef3d141b6'
down_revision = '2566e1460825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study')
    op.drop_table('patient')
    # ### end Alembic commands ###
