"""user table

Revision ID: 2566e1460825
Revises: 
Create Date: 2020-12-16 18:46:51.925442

"""
from alembic import op
import sqlalchemy as sa
import pandas as pd
import hashlib
import os

# revision identifiers, used by Alembic.
revision = '2566e1460825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
                                 sa.Column('id', sa.Integer(), nullable=False),
                                 sa.Column('email', sa.String(length=128), nullable=True),
                                 sa.Column('first_name', sa.String(length=128), nullable=True),
                                 sa.Column('family_name', sa.String(length=128), nullable=True),
                                 sa.Column('role', sa.String(length=128), nullable=True),
                                 sa.Column('key', sa.LargeBinary(), nullable=True),
                                 sa.Column('salt', sa.LargeBinary(), nullable=True),
                                 sa.Column('recovery_key', sa.LargeBinary(), nullable=True),
                                 sa.Column('recovery_status', sa.Integer(), nullable=True),
                                 sa.Column('log_out', sa.Boolean(), nullable=True),
                                 sa.PrimaryKeyConstraint('id')
                                 )

    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_family_name'), 'user', ['family_name'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###

    users = pd.read_csv('data/users.csv')
    users_data = []
    for row in range(len(users)):
        # hash password
        password = users.loc[row, 'password']
        salt = os.urandom(32)  # A new salt for this user
        key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)

        # save user
        users_data.append({
            'id': int(users.loc[row, 'id']),
            'email': users.loc[row, 'email'],
            'key': key,
            'salt': salt,
            'first_name': users.loc[row, 'first_name'],
            'family_name': users.loc[row, 'family_name'],
            'role': users.loc[row, 'role']})

    op.bulk_insert(
        user_table,
        users_data
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_family_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
