"""add state fields

Revision ID: bf7657f1ff12
Revises: d3c80b8a003f
Create Date: 2021-04-21 17:21:47.967544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7657f1ff12'
down_revision = 'd3c80b8a003f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('preview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'preview')
    # ### end Alembic commands ###
