"""add state fields

Revision ID: d3c80b8a003f
Revises: 0a0cfb6815c6
Create Date: 2021-04-20 21:32:04.608028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c80b8a003f'
down_revision = '0a0cfb6815c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'order')
    # ### end Alembic commands ###
