"""2021-01-26 create instance table

Revision ID: d6874accfa9d
Revises: 0496f7402fa3
Create Date: 2021-01-26 21:10:42.221457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6874accfa9d'
down_revision = '0496f7402fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('study_id', sa.String(length=128), nullable=True),
    sa.Column('orientation', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance')
    # ### end Alembic commands ###
