version: '3.3'
services:
  db-phleb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=phlb_viewer
      - POSTGRES_PASSWORD=phlb_viewer
      - POSTGRES_DB=phlb_viewer
    networks:
      - phlebology_helper_network

  core-api-phleb:
    container_name: core-api-phleb
    ports:
      - "8992:80"
    build: ./core-api
    environment:
      - UWSGI_INI=uwsgi.ini
      - PRE_START_PATH=/usr/src/phlebology-helper-backend/prestart.sh
      - DATABASE_URL=postgresql://phlb_viewer:phlb_viewer@db-phleb/phlb_viewer
    networks:
      - phlebology_helper_network



networks:
  phlebology_helper_network:
    driver: bridge