version: '3.3'
services:
  db-phleb:
    image: postgres
    environment:
      - POSTGRES_USER=phlb_viewer
      - POSTGRES_PASSWORD=phlb_viewer
      - POSTGRES_DB=phlb_viewer
    networks:
      - phlebology_helper_network

  core-api-phleb:
    container_name: core-api-phleb
    ports:
      - "8992:443"
      - "8991:80"
    build: ./core-api
    environment:
      - UWSGI_INI=uwsgi.ini
      - PRE_START_PATH=/usr/src/phlebology-helper-backend/prestart.sh
      - DATABASE_URL=postgresql://phlb_viewer:phlb_viewer@db-phleb/phlb_viewer
    networks:
      - phlebology_helper_network
    volumes:
      - /etc/letsencrypt/live/exgratia.ru/privkey.pem:/etc/letsencrypt/live/exgratia.ru/privkey.pem
      - /etc/letsencrypt/live/exgratia.ru/fullchain.pem:/etc/letsencrypt/live/exgratia.ru/fullchain.pem


networks:
  phlebology_helper_network:
    driver: bridge