---
swagger: "2.0"
info:
  description: "Phlebology helper Project"
  version: "1.0.0"
  title: "Phlebology helper Project"
basePath: "/api"
tags:
- name: "auth"
  description: "Authorization"
- name: "user"
  description: "UserInfo"
- name: "patient"
  description: "patientInfo"
- name: "dicom"
  description: "dicomInfo"
- name: "series"
  description: "seriesInfo"
- name: "study"
  description: "studyInfo"
schemes:
- "https"
- "http"
paths:
  /dicom/{id}:
    get:
      tags:
      - "dicom"
      summary: "Download dicom image"
      operationId: "download_dicom"
      parameters:
      - in: "path"
        type: string
        name: "id"
        description: "Studi id"
        required: true
      responses:
        "200":
          description: "preview"
          schema:
            type: file
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.dicom_controller"
  /dicom/{id}/preview:
    get:
      tags:
      - "dicom"
      summary: "Preview dicom image"
      operationId: "preview"
      parameters:
      - in: "path"
        type: string
        name: "id"
        description: "Studi id"
        required: true
      responses:
        "200":
          description: "preview"
          schema:
            type: string
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.dicom_controller"
  /series/{seriesId}/state.json:
    get:
      tags:
      - "series"
      summary: "Get series state"
      operationId: "get_state"
      parameters:
      - in: "path"
        type: string
        name: "seriesId"
        description: "Series id"
        required: true
      responses:
        "200":
          description: "get serie state"
          schema:
            type: object
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.series_controller"

  /series/{seriesId}/state:
    post:
      tags:
      - "series"
      summary: "Upload series state"
      operationId: "upload_state"
      parameters:
      - in: "path"
        type: string
        name: "seriesId"
        description: "Series id"
        required: true
      - in: "body"
        name: "state"
        description: "State"
        required: true
        schema:
          type: object
      responses:
        "200":
          description: "ok"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.series_controller"

  /patient/{patientId}/studies/list:
    get:
      tags:
      - "patient"
      summary: "Get patients ids"
      operationId: "get_studies"
      parameters:
      - in: "path"
        type: string
        name: "patientId"
        description: "Patient id"
        required: true
      responses:
        "200":
          description: "Studies"
          schema:
            type: array
            items:
              $ref: "#/definitions/Study"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.patient_controller"

  /series/{seriesId}:
    get:
      tags:
      - "series"
      summary: "Get series by id"
      operationId: "get_series_by_id"
      parameters:
      - in: "path"
        type: string
        name: "seriesId"
        description: "series id"
        required: true
      responses:
        "200":
          description: "Series"
          schema:
            $ref: "#/definitions/Series"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.series_controller"

  /studies/{studyId}:
    get:
      tags:
      - "study"
      summary: "Get study by id"
      operationId: "get_study_by_id"
      parameters:
      - in: "path"
        type: string
        name: "studyId"
        description: "Study id"
        required: true
      responses:
        "200":
          description: "Study"
          schema:
            $ref: "#/definitions/Study"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.study_controller"

  /patient/list:
    get:
      tags:
      - "patient"
      summary: "Get patients ids"
      operationId: "get_patients_ids"
      parameters: []
      responses:
        "200":
          description: "Patients id"
          schema:
            type: array
            items:
              $ref: "#/definitions/Patient"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.patient_controller"

  /patient/{id}:
    get:
      tags:
      - "patient"
      summary: "Get patient by id"
      operationId: "get_patient"
      parameters:
      - in: "path"
        type: string
        name: "id"
        description: "Patient id"
        required: true
      responses:
        "200":
          description: "Patient"
          schema:
            $ref: "#/definitions/Patient"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.patient_controller"

  /user/info:
    get:
      tags:
      - "user"
      summary: "Get user info"
      operationId: "get_user_info"
      parameters: []
      responses:
        "200":
          description: "User info"
          schema:
            $ref: "#/definitions/TokenData"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /auth/login/email:
    post:
      tags:
      - "auth"
      summary: "User login"
      operationId: "login"
      parameters:
      - in: "body"
        name: "body"
        description: "User data"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        "200":
          description: "JWT token"
          schema:
            $ref: "#/definitions/TokenData"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
  /auth/logout:
    post:
      tags:
      - "auth"
      summary: "User logout"
      operationId: "logout"
      parameters: []
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid status value"
      security:
      - JWT: []
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
  /auth/password/change:
    post:
      tags:
      - "auth"
      summary: "User change password"
      operationId: "change_password"
      parameters:
      - name: "email"
        in: "query"
        description: "User email"
        required: true
        type: "string"
      - name: "newPassword"
        in: "query"
        description: "User new password"
        required: true
        type: "string"
      - name: "recoveryCode"
        in: "query"
        description: "Recovery code from recovery letter"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
  /auth/password/recovery:
    post:
      tags:
      - "auth"
      summary: "Recovery password"
      operationId: "recovery_password"
      parameters:
      - name: "email"
        in: "query"
        description: "User email"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
  /auth/password/recovery/check:
    post:
      tags:
      - "auth"
      summary: "Recovery password check"
      operationId: "check_recovery_password"
      parameters:
      - name: "email"
        in: "query"
        description: "User email"
        required: true
        type: "string"
      - name: "recoveryCode"
        in: "query"
        description: "Recovery code from recovery letter"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
securityDefinitions:
  JWT:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-apikeyInfoFunc: "swagger_server.controllers.auth_controller.decode_token"
definitions:
  TokenData:
    type: "object"
    properties:
      token:
        type: "string"
      accessExpiresIn:
        type: "integer"
      email:
        type: "string"
      first_name:
        type: "string"
      family_name:
        type: "string"
      role:
        type: "string"
    example:
      role: "role"
      accessExpiresIn: 0
      first_name: "first_name"
      family_name: "family_name"
      email: "email"
      token: "token"
  UserData:
    type: "object"
    properties:
      password:
        type: "string"
      email:
        type: "string"

  Series:
    type: "object"
    properties:
      id:
        type: "string"
      orientation:
        type: "string"
      hasState:
        type: boolean
      instances:
        type: array
        items:
          $ref: "#/definitions/Instance"

  Study:
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
      series:
        type: array
        items:
          $ref: "#/definitions/Series"
      studyDate:
        type: "string"
        format: "date-time"

  Instance:
    type: "object"
    properties:
      id:
        type: "string"
      preview:
        type: string

  Patient:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      studies:
        type: array
        items:
          $ref: "#/definitions/Study"
